services:
  # Это хрестоматийный сервис внутри компоуза. Используйте его как шаблон. 
  test:
    ports:
      - "8000:8000" # Слева - выходящий порт (по которому можете со своего компа обратиться), справа внутренний порт (на который само приложение внутри контейнера обращается)
    build:
      context: .
      dockerfile: Dockerfile
    command: go run /app/cmd/api/main.go
    restart: unless-stopped
    container_name: test_go
  auth_go_db:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - ./migrations/event.sql:/docker-entrypoint-initdb.d/event.sql
      - ./database/event:/var/lib/postgresql/data
    container_name: test_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    container_name: event_redis
    ports:
      - "6379:6379"
  # Рэббит поднимать лучше отдельно, потому что по нему будут общаться многие сервисы. Так что помещать его в docker-compose бессмысленно.