Postgres:
  user: "root"
  password: "qwerty_123"
  host: "37.18.110.184"
  port: "5432"
  dbName: "postgres"

System:
  service_name: "test-pkg"
  fernet_key: "fcGak6T093fEjAfd4c291IlTSVFAeLnr-e58ZcJo3Ok=" # https://8gwifi.org/CipherFunctionality
